[package]
name = "starmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
auto_ops = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
assert_float_eq = "1"
